apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/savvy-camp-425418-t5/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_SERVICE_IP
          value: "34.44.199.121"  # Replace with your actual backend service DNS name
      imagePullSecrets:
      - name: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

